# Create a copy of this file called mail.yml, with settings filled in depending
# on which environment the app is running in (development or production).
#
# DO NOT COMMIT MAIL.YML TO VERSION CONTROL.
#
# For deployment at UIUC, PSAP already has working development & production
# email accounts which can be plugged in here. Contact a project member for
# details.

development:
  address: psap@example.org
  from: 'Preservation Self-Assessment Program <psapdev@yahoo.com>'
  delivery_method: smtp
  smtp_host: smtp.mail.yahoo.com
  smtp_port: 587
  username: psapdev@yahoo.com
  password:
  authentication: plain
  enable_starttls_auto: true

test:
  address: psap@example.org
  from: 'Preservation Self-Assessment Program <psap@example.org>'
  delivery_method: smtp
  smtp_host: smtp.example.org
  smtp_port: 123
  username: psap@example.org
  password: cats
  authentication: plain
  enable_starttls_auto: false

staging:
  address: psap@library.illinois.edu
  from: 'Preservation Self-Assessment Program <psap@library.illinois.edu>'
  delivery_method: smtp
  smtp_host: <%= begin IO.read("/home/psap/.mail_host") rescue "" end %>
  smtp_port: <%= begin IO.read("/home/psap/.mail_port") rescue "" end %>
  username: <%= begin IO.read("/home/psap/.mail_username") rescue "" end %>
  password: <%= begin IO.read("/home/psap/.mail_password") rescue "" end %>
  authentication: plain
  enable_starttls_auto: false

production:
  address: psap@library.illinois.edu
  from: 'Preservation Self-Assessment Program <psap@library.illinois.edu>'
  delivery_method: smtp
  smtp_host: <%= begin IO.read("/home/psap/.mail_host") rescue "" end %>
  smtp_port: <%= begin IO.read("/home/psap/.mail_port") rescue "" end %>
  username: <%= begin IO.read("/home/psap/.mail_username") rescue "" end %>
  password: <%= begin IO.read("/home/psap/.mail_password") rescue "" end %>
  authentication: plain
  enable_starttls_auto: false
