# Create a copy of this file called psap.yml, with settings filled in depending
# on which environment the app is running in (development or production).
#
# DO NOT COMMIT PSAP.YML TO VERSION CONTROL.

development:
  :test_institution_id: 1
  :recaptcha:
    :public_key: ''
    :secret_key: ''

test:
  :test_institution_id: 1
  :recaptcha:
    :public_key: ''
    :secret_key: ''

production:
  :test_institution_id: 1
  :recaptcha:
    :public_key: ''
    :secret_key: ''
