# Create a copy of this file called psap.yml, with settings filled in depending
# on which environment the app is running in (development or production).
#
# DO NOT COMMIT PSAP.YML TO VERSION CONTROL.

development:
  :test_institution_id: 1
  :results_per_page: 50
  :mail_address: psap@example.org
  :mail_from: 'Preservation Self-Assessment Program <psap@example.org>'
  :mail_delivery_method: smtp
  :mail_smtp_host:
  :mail_smtp_port:
  :mail_username:
  :mail_password:
  :mail_authentication: plain
  :mail_enable_starttls_auto: true
  :recaptcha_public_key:
  :recaptcha_secret_key:

test:
  :test_institution_id: 1
  :results_per_page: 50
  :mail_address: psap@example.org
  :mail_from: 'Preservation Self-Assessment Program <psap@example.org>'
  :mail_delivery_method: smtp
  :mail_smtp_host:
  :mail_smtp_port:
  :mail_username:
  :mail_password:
  :mail_authentication: plain
  :mail_enable_starttls_auto: false
  :recaptcha_public_key:
  :recaptcha_secret_key:

production:
  :test_institution_id: 1
  :results_per_page: 50
  :mail_address: psap@example.org
  :mail_from: 'Preservation Self-Assessment Program <psap@example.orgu>'
  :mail_delivery_method: smtp
  :mail_smtp_host:
  :mail_smtp_port:
  :mail_username:
  :mail_password:
  :mail_authentication: plain
  :mail_enable_starttls_auto:
  :recaptcha_public_key:
  :recaptcha_secret_key: